### ISSUE TITLE
Limit time aggregation options

### ISSUE THREAD

**Issue by Buesi** [shafy/fugu#14]
Some aggregation levels don't make sense based on the time range selected. We already limit selecting "Day" as aggregation if the time range is longer than 6 days. Now, we should also add the following:

- when time range of "last 7 days" is selected, options "year" and "month" should be disabled
- when time range of "this month" is selected, option "year" should be disabled
- when time range of "last 30 days" is selected, option "year" should be disabled

**Comment by shafy** [comment]
Fixed in #15
