### ISSUE TITLE
Disallow certain property values

### ISSUE THREAD

**Issue by shafy** [shafy/fugu#18]
Currently, users can arbitrarly add property values. This means that they can also save personally identifiable information (PII) like email addresses or ip addresses. While we can't possibly prevent every piece of PII, we should "blacklist" some obvious ones.

I suggest adding validation that checks for email addresses and IP addresses to start with.

**Comment by Buesi** [comment]
what do you think about this list as excluded from property names (in addition to all): 
email e-mail IP address phone

is it possible to check in these cases if the name only contains these texts or do we check if it's exactly this word? if we check not exact, we need a separate method

**Comment by shafy** [comment]
Let's check only exact matches for now. Let's also add `"phone_number"`.

**Comment by Buesi** [comment]
and phone-number ?

**Comment by shafy** [comment]
Yes sure, you can add a couple of variants.
