### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by nikodunk** [shafy/fugu#4]
When I hit the endpoint `POST https://app.fugu.lol/api/v1/events` as referenced in the README with the body

```
{
  api_key: my_api_key
  name: 'Clicked Contact'
  properties: {userId: 'niko'}
}
```

I receive the response

```
{
    "error": {
        "type": "NoMethodError",
        "message": "undefined method `titleize' for nil:NilClass"
    }
}
```

**Comment by shafy** [comment]
Thanks @nikodunk for reporting. I'll look into it!

**Comment by shafy** [comment]
@nikodunk can you try to to post your data with CURL or Postman or something, and send me your command or Postman body?
Also, can you retry with your integration (I've added Sentry, so I can better undertand the error for you).

Thanks!

**Comment by shafy** [comment]
This issue should be fixed. Let me know if it happens again @nikodunk.

**Comment by nikodunk** [comment]
It is solved! Thank you for your help @shafy
